### ISSUE TITLE
Design kit access request

### ISSUE THREAD

**Issue by kosruben** [carbon-design-system/ibm-dotcom-library-design-kit#33]
Thanks for your interest in the IBM.com Design kits!

We are in a closed adoption phase at the moment. Please answer the following questions to help us better understand your interest. Someone from Carbon for IBM.com will reach out to you soon regarding your request for access.

> Which team are you on?

Global ISV Ecosystem

> What experience are you designing for?

Landing pages for IBM.com (https://www.ibm.com/partners/start/)

> Please list a point of contact for:

Offering manager
_Jane Kim_

Design lead
_Ruben Kos_

Development lead
_Mark Wallace_

**Comment by JennySanchez** [comment]
@oliviaflory FYI on this request existed.

**Comment by oliviaflory** [comment]
Ruben has been added to the box folder, closing this request.
