### ISSUE TITLE
Design kit access request

### ISSUE THREAD

**Issue by Snakepp** [carbon-design-system/ibm-dotcom-library-design-kit#42]
Thanks for your interest in the IBM.com Design kits!

We are in a closed adoption phase at the moment. Please answer the following questions to help us better understand your interest. Someone from Carbon for IBM.com will reach out to you soon regarding your request for access.

> Which team are you on?
IBM Systems DevOps team

> What experience are you designing for?
SWAT tool for providing access across all IBM Systems tools

> What platform is your experience on? (ie. Drupal, Wordpress, etc)
Vaadin

> Please list a point of contact for:
Offering manager
Vince Kerhin(vkerhin@us.ibm.com)
Design lead

Development lead
Jose.Pelayo@ibm.com

> Any additional information you'd like to share about your project
Internal project for IBM

**Comment by Snakepp** [comment]
any stats on this one?
We are looking into integrate our application internally with carbon design and going into lots of meetings with Customers like Z and Power.

We need a way to show with our mockups/wireframes with sketch and use this components to show how the internal IBM Web application will look like.

**Comment by oliviaflory** [comment]
Access granted
