### ISSUE TITLE
Design kit access request

### ISSUE THREAD

**Issue by ilrina** [carbon-design-system/ibm-dotcom-library-design-kit#43]
Thanks for your interest in the IBM.com Design kits!

We are in a closed adoption phase at the moment. Please answer the following questions to help us better understand your interest. Someone from Carbon for IBM.com will reach out to you soon regarding your request for access.

> Which team are you on?
Corporate marketing

> What experience are you designing for?
ibm.com and ibm.com/smart

> What platform is your experience on? (ie. Drupal, Wordpress, etc)
Hand-coded

> Please list a point of contact for:
Offering manager: Lance Tappana
Design lead: I am a design lead, Irina Lubenskaya
Development lead: Ryan Sebade

> Any additional information you'd like to share about your project

**Comment by ljcarot** [comment]
@oliviaflory Please go ahead and provide Irina with access to the Design kits.  Thanks!

**Comment by oliviaflory** [comment]
Added!
