### ISSUE TITLE
Design kit access request

### ISSUE THREAD

**Issue by saurabhkr9** [carbon-design-system/ibm-dotcom-library-design-kit#44]
Thanks for your interest in the IBM.com Design kits!

We are in a closed adoption phase at the moment. Please answer the following questions to help us better understand your interest. Someone from Carbon for IBM.com will reach out to you soon regarding your request for access.

> Which team are you on?

> What experience are you designing for?

> What platform is your experience on? (ie. Drupal, Wordpress, etc)

> Please list a point of contact for:
Offering manager
Design lead
Development lead

> Any additional information you'd like to share about your project

**Comment by oliviaflory** [comment]
Hi @saurabhkr9 is this for an internal or external website? Thank you!

**Comment by saurabhkr9** [comment]
Hi @oliviaflory Right now developing for my localhost, after the testing it'll deploy for Internal use(For RDC India project). So basically this is for internal website.

**Comment by ljcarot** [comment]
For internal websites, you should investigate here: w3 design system at https://w3.ibm.com/w3ds/docs/

**Comment by oliviaflory** [comment]
Closing this issue, per above, internal website should use w3 design.
