### ISSUE TITLE
Design kit access request

### ISSUE THREAD

**Issue by Philusha1983** [carbon-design-system/ibm-dotcom-library-design-kit#45]
Thanks for your interest in the IBM.com Design kits!

We are in a closed adoption phase at the moment. Please answer the following questions to help us better understand your interest. Someone from Carbon for IBM.com will reach out to you soon regarding your request for access.

> Which team are you on?
IBM Research HRL

> What experience are you designing for?
Website

> What platform is your experience on? (ie. Drupal, Wordpress, etc)
Wordpress, Webflow, HTML CSS

> Please list a point of contact for:
Offering manager: Chani Sacharen
Design lead: Philip Levin Slesarev
Development lead: Niva Bar-Shimon

> Any additional information you'd like to share about your project

**Comment by ljcarot** [comment]
Is this for internal or external website?

**Comment by Philusha1983** [comment]
I'm going to work on some of the external pages of our [research lab.](http://www.research.ibm.com/labs/haifa/index.shtml)
for now, I'm diving into the materials that I can get and use.
@ljcarot

**Comment by ljcarot** [comment]
@oliviaflory will be sending access to you and @RobertaJHahn will set up an adopter call and send you a questionnaire.  Thanks @Philusha1983 Philip! cc: @wonilsuhibm @jeffchew

**Comment by Philusha1983** [comment]
@ljcarot @oliviaflory 
Can you send it to my IBM email?
philip.levin-slesarev@ibm.com
thanks!

**Comment by oliviaflory** [comment]
@Philusha1983 added you to the box folder
