### ISSUE TITLE
Design kit access request

### ISSUE THREAD

**Issue by richardhomewood** [carbon-design-system/ibm-dotcom-library-design-kit#46]
Hello,

I am a Tech Director over at an agency called AKQA and we are working with Ken Hartmann as a client at IBM on a number of web projects.

Our designer has requested access to the design files that support the IBM Carbon React component library - would it be possible for you to share these with us?

Thank you!

Rich

**Comment by oliviaflory** [comment]
Hi Rich, 
Do you and your designers have access to IBM internal box folders? In the past some agency teams have been given IBM emails for this purpose.

**Comment by richardhomewood** [comment]
Hi @oliviaflory, thanks for getting back so quickly - yes, we do; my IBM email is richard.homewood@ibm.com

Thanks
Rich

**Comment by oliviaflory** [comment]
Great, I will add you to the Box folder! 

You might find our website useful as well: https://ibm-dotcom-library.mybluemix.net/

**Comment by diegomarcuz** [comment]
@RobertaJHahn, is this for me ?

**Comment by richardhomewood** [comment]
Received with thanks @oliviaflory and @RobertaJHahn - closing this ticket
