### ISSUE TITLE
Design kit access request

### ISSUE THREAD

**Issue by rafaelamascaro-star** [carbon-design-system/ibm-dotcom-library-design-kit#47]
Thanks for your interest in the IBM.com Design kits!

We are in a closed adoption phase at the moment. Please answer the following questions to help us better understand your interest. Someone from Carbon for IBM.com will reach out to you soon regarding your request for access.

> Which team are you on?

MSC / Privacy Organization

> What experience are you designing for?

Application called Preference Center

> What platform is your experience on? (ie. Drupal, Wordpress, etc)

Carbon

> Please list a point of contact for:
Offering manager: Neera Mathur
Design lead: Rafaela Mascaro
Development lead: Joe Stowers

> Any additional information you'd like to share about your project

**Comment by ljcarot** [comment]
@oliviaflory Please provide access to kit cc: @jeffchew

**Comment by oliviaflory** [comment]
Hi @rafaelamascaro-star could you please share your IBM email so I can add you to the Box folder? Thank you!

**Comment by RobertaJHahn** [comment]
meeting scheduled to review the completed questionnaire Monday, 8/17.

**Comment by oliviaflory** [comment]
Invitation to design kit folder sent!
