### ISSUE TITLE
Design kit access request

### ISSUE THREAD

**Issue by assiroud** [carbon-design-system/ibm-dotcom-library-design-kit#50]
Thanks for your interest in the IBM.com Design kits!

We are in a closed adoption phase at the moment. Please answer the following questions to help us better understand your interest. Someone from Carbon for IBM.com will reach out to you soon regarding your request for access.

> Which team are you on?
IBM Sterling platform I AI Applications

> What experience are you designing for?
Web

> What platform is your experience on? (ie. Drupal, Wordpress, etc)
Wordpress, Netsuite

> Please list a point of contact for:
Offering manager bobt@ca.ibm.com

> Any additional information you'd like to share about your project

**Comment by oliviaflory** [comment]
Hi @assiroud could you share your IBM email so I can add you to the box folder?

**Comment by assiroud** [comment]
assiroud@ca.ibm.com
Thanks !

**Comment by oliviaflory** [comment]
Thank you, added!
