### ISSUE TITLE
Design kit access request

### ISSUE THREAD

**Issue by pavolprok** [carbon-design-system/ibm-dotcom-library-design-kit#52]
Thanks for your interest in the IBM.com Design kits!

We are in a closed adoption phase at the moment. Please answer the following questions to help us better understand your interest. Someone from Carbon for IBM.com will reach out to you soon regarding your request for access.

> Which team are you on?
MSC Design

> What experience are you designing for?

Web
> What platform is your experience on? (ie. Drupal, Wordpress, etc)
Flat HTML, Drupal

> Please list a point of contact for:
Offering manager - Nicoleta Costache
Design lead - Katie Andresen
Development lead

> Any additional information you'd like to share about your project

**Comment by oliviaflory** [comment]
Hi @pavolprok could you please provide your IBM email and I'll add you to the box folder?

**Comment by pavolprok** [comment]
> Hi @pavolprok could you please provide your IBM email and I'll add you to the box folder?

pavol_prok@sk.ibm.com

Thank you

**Comment by oliviaflory** [comment]
Added to box folder
