### ISSUE TITLE
Design kit access request

### ISSUE THREAD

**Issue by mariuszmickiewicz** [carbon-design-system/ibm-dotcom-library-design-kit#53]
> Which team are you on?

IBM Watson Media

> What experience are you designing for?

I work on Native Mobile Kit with Peter Garvin and I also assist Carbon team with maintaining their libraries. Currently not working on any IBM.com pages (but our unit have a dozen which could be refreshed), but would like to see the library to be up to date and informed with all the design kits at IBM. Thanks.

I will share my email on Slack.

**Comment by oliviaflory** [comment]
Added to box folder
