### ISSUE TITLE
Design kit access request

### ISSUE THREAD

**Issue by sorin-calinescu** [carbon-design-system/ibm-dotcom-library-design-kit#58]
Thanks for your interest in the `IBM.com Design Adopter Kit`!

We are in a closed adoption phase at the moment. Please answer the following questions to help us better understand your interest. Someone from `Carbon for IBM.com` will reach out to you soon regarding your request for access.

> What is your email address?
sorin.calinescu@ro.ibm.com

> Which team are you on?
Marketing Services Center, Bucharest
Design Practice

> What experience are you designing for?
Marketing project (web page for client offering)

> What platform is your experience on? (ie. Drupal, Wordpress, etc)
Flat server

> Please list a point of contact for:
Offering manager
Design lead
Development lead

nicoleta.costache@ro.ibm.com

> Please share any additional information you'd like to share about your project?

**Comment by oliviaflory** [comment]
Added to Box!
