### ISSUE TITLE
Design kit: data table default cells

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-dotcom-library-design-kit#6]
Add additional default cells to design kit
- 04 selected
- 05 selected-hover
- 06 disabled

Acceptance criteria:
- [ ] white theme 
- [ ] gray 10 theme
- [ ] gray 90 theme
- [ ] gray 100 theme

**Comment by ljcarot** [comment]
@oliviaflory Stalebot identified this as inactive, should we close or move it to backlog?

**Comment by oliviaflory** [comment]
@ljcarot let's move to backlog, we still need it.

**Comment by oliviaflory** [comment]
Not stale

**Comment by oliviaflory** [comment]
not stale
